# Generated by Django 2.2.4 on 2019-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='god', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, verbose_name='性别')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y%m', verbose_name='用户头像')),
                ('hobby', models.CharField(default='喝咖啡', max_length=1000, verbose_name='爱好')),
                ('life_maxim', models.CharField(default='宁愿做过了后悔，也不要错过了后悔。', max_length=1000, verbose_name='人生格言')),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
                'db_table': 'customers',
            },
        ),
    ]
